trigger:
  - master
  
pool: Default

stages:
- stage: build
  jobs:
  - job: Api
    variables:
      buildConfiguration: 'Release'
    
    displayName: Build Api

    steps:
    - task: UseDotNet@2
      displayName: 'Use .Net Core sdk '
      inputs:
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: AzureADSample.Api
        arguments: '-c $(buildConfiguration)'
          
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        workingDirectory: AzureADSample.Api
      
    - publish: $(build.artifactstagingdirectory)/AzureADSample.Api
      artifact: api

  - job: Website
    displayName: Build Website

    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: 10.x

    - script: npm install -g @angular/cli && npm install && npm run build
      workingDirectory: AzureADSample.Website
      displayName: 'website: npm install and build'

    - publish: AzureADSample.Website/dist
      artifact: website
