name: $(Date:yyMM).$(DayOfMonth)$(Rev:.r)
  
trigger:
  - master
  
pool: Default

variables:
  AzureSubscription: Azure Chris MPN - AzureAdSample

stages:
- stage: build
  jobs:
  - job: API
    displayName: Build API
  
    variables:
      buildConfiguration: Release
    
    steps:
    - task: UseDotNet@2
      displayName: Use .Net Core sdk
      inputs:
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        projects: AzureADSample.Api
        arguments: -c $(buildConfiguration) -p:AssemblyVersion=$(Build.BuildNumber)
          
    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      inputs:
        command: publish
        arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/api
        modifyOutputPath: false
        workingDirectory: AzureADSample.Api

    - publish: $(build.artifactstagingdirectory)/api
      artifact: api

  - job: Website
    displayName: Build Website

    steps:
    - task: NodeTool@0
      displayName: Install Node.js
      inputs:
        versionSpec: 10.x

    - script: npm install -g @angular/cli && npm install && npm run build
      workingDirectory: AzureADSample.UI
      displayName: npm install and build

    - publish: AzureADSample.UI/dist/browser
      artifact: website

  - job: Functions
    displayName: Build Functions

    variables:
      buildConfiguration: Release

    steps:
    - task: UseDotNet@2
      displayName: Use .Net Core sdk
      inputs:
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        projects: AzureADSample.Functions
        arguments: -c $(buildConfiguration) -p:AssemblyVersion=$(Build.BuildNumber)
          
    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      inputs:
        command: publish
        arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/functions
        modifyOutputPath: false
        workingDirectory: AzureADSample.Functions

    - publish: $(build.artifactstagingdirectory)/functions
      artifact: functions

- stage: qa
  jobs:
  - deployment: qa
    variables:
      WebsiteClientId: a36db5a2-1bd7-4b40-9e05-33bce3ff7f0a
      ApiClientId: 2a90d9f4-053f-4c76-ad3c-099cb0f35595
      ApiUrl: https://multitenantazuread-api.azurewebsites.net/

      ApiAppName: multitenantazuread-api
      FunctionsAppName: multitenantazuread-functions
      WebsiteStorage: multitenantazuread

      TenantId: b60cd469-51bd-4b39-a9f7-3140752ed3d9
      FunctionsClientId: 0e841e38-82fd-4cc3-9a9e-1758d4d5d796
      #FunctionsClientSecret:

      # Website config.json
      auth.clientId: $(WebsiteClientId)
      auth.scope: openid profile email api://$(ApiClientId)/.default
      baseApiUrl: $(ApiUrl)
      version: $(Build.BuildNumber)
      
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
            - template: azure-deployment-steps.yml
