steps:
  - task: FileTransform@1
    displayName: Configure Website
    inputs:
      folderPath: $(Pipeline.Workspace)/website/
      fileType: json
      targetFiles: config.json

  - task: AzureFileCopy@2
    displayName: Deploy Website
    inputs:
      SourcePath: $(Pipeline.Workspace)/website
      azureSubscription: $(AzureSubscription)
      Destination: AzureBlob
      storage: $(WebsiteStorage)
      ContainerName: $web

  - task: AzureRmWebAppDeployment@4
    displayName: Deploy API
    inputs:
      azureSubscription: $(AzureSubscription)
      appType: webAppLinux
      WebAppName: $(ApiAppName)
      packageForLinux: $(Pipeline.Workspace)/api/api.zip
      AppSettings: |
        -Auth__Audience "$(ApiClientId)"

  - task: AzureFunctionApp@1
    displayName: Deploy Functions
    inputs:
      azureSubscription: $(AzureSubscription)
      appType: functionAppLinux
      package: $(Pipeline.Workspace)/functions/functions.zip
      appName: $(FunctionsAppName)
      AppSettings: |
        -BaseApiUrl "$(baseApiUrl)"
        -Scopes "api://$(ApiClientId)/.default"
        -AzureAd__Instance "https://login.microsoftonline.com/"
        -AzureAd__TenantId "$(TenantId)"
        -AzureAd__ClientId "$(FunctionsClientId)"
        -AzureAd__ClientSecret "$(FunctionsClientSecret)"
